baseurl = "celtoys.co.uk"
languageCode = "en-uk"
title = "Celtoys"

[params]
  name = "Celtoys"
  description = "Celtoys"

  [params.about]
    title = "about"
    bio = "bio **bio**"
  
  [params.work]
    title = "work"
